// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testAPI.Models;

#nullable disable

namespace testAPI.Migrations
{
    [DbContext(typeof(ExoDbContext))]
    [Migration("20240410110132_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("testAPI.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int?>("ClientId1")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId1");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            FirstName = "Cedric",
                            LastName = "DELMAS"
                        },
                        new
                        {
                            ClientId = 2,
                            FirstName = "Flo",
                            LastName = "TOCCO"
                        },
                        new
                        {
                            ClientId = 3,
                            FirstName = "Oli",
                            LastName = "KOENIG"
                        });
                });

            modelBuilder.Entity("testAPI.Models.Client", b =>
                {
                    b.HasOne("testAPI.Models.Client", null)
                        .WithMany("ListClients")
                        .HasForeignKey("ClientId1");
                });

            modelBuilder.Entity("testAPI.Models.Client", b =>
                {
                    b.Navigation("ListClients");
                });
#pragma warning restore 612, 618
        }
    }
}
